## Data Analysis
- SQL
- Devloper - MNC
- Power BI - charts
- Insights - Reports and Charts


## Data scientist

- There were using exel sheets before
- Python - numpy, pandas
- Scale - Millions of rows
- Scikit - Data prediction
- Matplot, seaborn - charts
- line by line (Step)


In [ ]:
import numpy as np


## numpy

- workign with arrays (1D)
- Performant (Compared Python List)
- C language
- Statistical oriented - mean, median, mode

In [3]:
marks1 = [90, 80, 20, 40]
print(marks1*2)

[90, 80, 20, 40, 90, 80, 20, 40]


In [ ]:
marks2 = np.array([90, 80, 20, 40])
print(marks2*2) # catering - Data scientist

[180 160  40  80]


In [6]:
marks1 = [90, 80, 20, 40]
print([x*2 for x in marks1])

[180, 160, 40, 80]


In [ ]:
np.ones(10) # identity matrix
np.zeros(10) # identity matrix for addition

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# array of 20 5's
np.zeros(20)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5.])

## operation
- Multiple, Division, Addition, Subtraction
- Boolean, 

In [ ]:
np.arange(1, 11)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1, 11, 2) + np.arange(1, 11, 2)


array([ 2,  6, 10, 14, 18])

In [21]:
[9,2,3] + [1,2,5]

[9, 2, 3, 1, 2, 5]

## Boolean (Matrix/mask)

In [31]:
first_tens_nums = np.arange(1, 11)
first_tens_nums[first_tens_nums > 5]

array([ 6,  7,  8,  9, 10])

In [32]:
even_num = np.arange(1, 201)
even_num[np.arange(1, 201) % 2 == 0]


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [33]:
np.arange(2, 201, 2)


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [35]:
ages = np.random.randint(18, 60, 5)
ages_list = ages.tolist()

print(ages_list)


[34, 22, 51, 46, 51]


## Performance

- numpy arrays are 100 - 1000 times the performance of python list
- %%time - time operation

## Statistical oriented - mean, mode, median, std



- mean -> average
- mode -> The most repeated value (most popular)
- median -> Middle value of the sorted array
- std -> measure of the spread/distribution of values...average between the mean and numbers

In [ ]:
marks = np.random.randint(40, 100, 10)
print(marks)
print(marks.mean()) # there are two ways of doing the mean
print(np.mean(marks))

[79 72 99 81 60 66 72 80 53 98]
76.0
76.0


In [40]:
print(np.median(marks))

75.5


In [42]:
print(np.sum(marks))

760


In [41]:
print(np.std(marks))

14.071247279470288


In [ ]:
# Task 1.1

'''
investment -> R1_000
rate_of_interest -> 5%
end of 2 years. What is the balance?
- 1st year R50 -> 1_050
- 2nd year R52.5 -> 1_102.5
'''

In [61]:
P = 1000
r = 0.05
years = np.arange(1, 11)

balances = P * (1+r)**years


print(balances)
print(balances[-1]) # Task 1.2
print(((balances[-1]- P)/P)*100)  # Task 1.3


[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]
1628.894626777442
62.8894626777442


### slicing
- Index 
- Negative Index
- Range





## Useful methods

- max, min, argmax, argmin
- flip, unique 
- String methods


In [ ]:
salaries = np.random.randint(1_000, 10_000, 10)
np.max(salaries)


np.int32(1026)

In [65]:
np.min(salaries)


np.int32(1026)

In [66]:
np.argmax(salaries)

np.int64(3)

In [69]:
nums = np.random.randint(1, 4, 10)
np.unique(nums)
np.flip(nums)

array([3, 3, 2, 2, 1, 1, 3, 3, 1, 2], dtype=int32)

In [ ]:
hourly_visitors = [468, 279, 73, 272, 406, 128, 302, 216, 140, 82]

total_visitors = np.sum(hourly_visitors)

peak_hour = np.argmax(hourly_visitors)

average_visitors = np.mean(hourly_visitors)
print(f"Total visitors in the day: {total_visitors}")
print(
    f"Peak hour: {peak_hour + 1}"
)
print(
    f"Average people visit: {int(average_visitors)}"
)


Total visitors in the day: 2366
Peak hour: 1
Average people visit: 236


In [72]:
items = np.array(
    [
        " Apple",
        "banana ",
        "GRAPE",
        "cucumber",
        "Pineapple",
        " tomato ",
        "Orange",
        " lemon",
        "Kiwi ",
        "mango",
        "blueberry ",
        " raspberry",
    ]
)

items = np.strings.strip(items)
items = np.strings.lower(items)
items = np.unique(items)
print(items)

['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


In [ ]:
# Task 3.1

print(items[np.char.startswith(items, 'b')])
print(items[np.char.count(items, 'e') == 1])


['banana' 'blueberry']
['apple' 'cucumber' 'grape' 'lemon' 'orange' 'raspberry']


## 2D Matrix / Arrays

In [88]:
num_3x3 = np.array([
    [1, 3, 4],
    [6, 10, 77],
    [9, 20, 24]
])
num_3x3

array([[ 1,  3,  4],
       [ 6, 10, 77],
       [ 9, 20, 24]])

In [89]:
num_3x3.shape

(3, 3)

In [ ]:
# arimathic operations works on 2D matrixs